#This script is used to load CPM signal counts for H3K4me1, H3K27ac at all naive and EpiLC H3K4me1 peaks and RNA CPMs for nearby genes for mutants and controls generated by Boileau et al 2023 Genome Biology.
#It will then calculate the median signal for each feature across supplied RT bins (derived from RT-analysis.R script). Resulting datasheet will then be used to generate plots of RT vs H3K4me1 and RNA shown in manuscript.

#Analysis replication Timing naive vs formative
library(preprocessCore)
library(DNAcopy)
library(viridis) #needed on cluster
library(readr) #needed on cluster
library(dplyr)
library(ggplot2)
library(umap)
library(RColorBrewer)
library(ComplexHeatmap)
library(regioneR)
library(BSgenome.Mmusculus.UCSC.mm10) #for GC content
library(chromoMap)

#Set up working directory
setwd("/blellochlab/data1/deniz/analysis/mll-rt-paper/")

#Load delta RT data
dRT <- read.table("/blellochlab/data1/deniz/analysis/mll-rt-paper/exports/RT-50kb-bins-loess.bed", header=T, sep ="\t")
dRT.gr <- makeGRangesFromDataFrame(dRT, keep.extra.columns = TRUE)

#Load and format epigenetics/RNA data at H3K4me1 peaks from Boileau et al 2023 Genome Biol
supermatrix.raw <- read_delim("/blellochlab/data1/deniz/go-data/analysis/repli-seq-mll34/withv65/bg/R/epigenetic-rna-data-ryan/supermatrix.k4m1.txt","\t", escape_double = FALSE, trim_ws = TRUE)
supermatrix <- data.frame(supermatrix.raw)
colnames(supermatrix)[1:3] <- c("Chr","Start","End")
supermatrix <- supermatrix[,-c(12:14,29:32,45:56,61:64,67:69,72:74,77:84,89)]
supermatrix$rna_fold_nf_dcd <- supermatrix$FdCD - supermatrix$NdCD
supermatrix$pk_fold_n_dcdwt_k4m1 <- supermatrix$N_dCD_k4m1 - supermatrix$N_WT_k4m1
supermatrix$pk_fold_n_kowt_k4m1 <- supermatrix$N_CKO_k4m1 - supermatrix$N_WT_k4m1
supermatrix.gr <- makeGRangesFromDataFrame(supermatrix, keep.extra.columns = TRUE)
columnsToAverage <- c(13:20,23:55) #Define columns to be summarized by median per 50kb RT bin

#Calculate median signal of each feature per 50kb RT bin
ovlp <- findOverlaps(dRT.gr,supermatrix.gr,ignore.strand=T)
averagedValues  <- apply(supermatrix[subjectHits(ovlp),columnsToAverage], 2, function(x) tapply(x, factor(queryHits(ovlp)), median,na.rm=T))
dRT[,colnames(averagedValues)] <- NA
dRT[unique(queryHits(ovlp)),44:ncol(dRT)] <- averagedValues

#Cleanup columns names
colnames(dRT)[44:ncol(dRT)] <- c(
  'RNA.AVGnaive.WT', 'RNA.AVGformative.WT', 'RNA.AVGnaive.KO', 
  'RNA.AVGformative.KO', 'RNA.AVGnaive.dKO', 'RNA.AVGformative.dKO', 'RNA.AVGnaive.dCD', 'RNA.AVGformative.dCD', 
  'dRNA.WT','dRNA.dKO', 'dRNA.naive.dKOvsWT', 'H3K4me1.AVGnaive.WT', 'H3K4me1.AVGformative.WT', 
  'H3K4me1.AVGnaive.KO','H3K4me1.AVGformative.KO', 'H3K4me1.AVGnaive.dKO', 'H3K4me1.AVGformative.dKO', 'H3K4me1.AVGnaive.dCD', 
  'H3K4me1.AVGformative.dCD', 'H3K27ac.AVGnaive.WT', 'H3K27ac.AVGformative.WT', 'H3K27ac.AVGnaive.dKO', 'H3K27ac.AVGformative.dKO', 
  'ATAC.AVGnaive.WT', 'ATAC.AVGformativeWT', 'ATAC.AVGnaive.dKO', 'ATAC.AVGformative.dKO', 'dH3K4me1.WT', 
  'dH3K27ac.WT', 'dH3K4me1.dKO', 'dH3K27ac.dKO', 'dH3K4me1.naive.dKOvsWT', 'dH3K27ac.naive.dKOvsWT', 
  'dH3K4me1.KO','dH3K4me1.dCD', 'dATAC.WT', 'dATAC.dKO', 'dATAC.naive.dKOvsWT', 
  'dRNA.dCD', 'dH3K4me1.naive.dCDvsWT', 'dH3K4me1.naive.KOvsWT'
)

#Add additional comparions
colnames(dRT)
dRT$dRT.naive.KOvsWT <- dRT$AVGnaive.KO - dRT$AVGnaive.WT
dRT$dRNA.KO <- dRT$RNA.AVGformative.KO - dRT$RNA.AVGnaive.KO
dRT$dRNA.naive.KOvsWT <- dRT$RNA.AVGnaive.KO - dRT$RNA.AVGnaive.WT
dRT$dRNA.naive.dCDvsWT <- dRT$RNA.AVGnaive.dCD - dRT$RNA.AVGnaive.WT
dRT$dRNA.naive.dKOvsKO <- dRT$RNA.AVGnaive.dKO - dRT$RNA.AVGnaive.KO
dRT$dRNA.naive.dCDvsKO <- dRT$RNA.AVGnaive.dCD - dRT$RNA.AVGnaive.KO
dRT$dH3K4me1.naive.dKOvsKO <- dRT$H3K4me1.AVGnaive.dKO - dRT$H3K4me1.AVGnaive.KO
dRT$dH3K4me1.naive.dCDvsKO <- dRT$H3K4me1.AVGnaive.dCD - dRT$H3K4me1.AVGnaive.KO

#Heatmaps
##delta RT, RNA and H3K4me1 (Signal difference EpiLC - naive) in mutant vs control at bins that change in control from naive to EpiLC (but do not change in mutants)
set.seed(178) 
input <- dRT[,c('chr','dH3K4me1.KO','dH3K4me1.dKO','dH3K4me1.dCD','dRT.KO','dRT.dKO','dRT.dCD','dRNA.KO','dRNA.dKO','dRNA.dCD')]
input <- input[complete.cases(input),]
s=0.5 #cutoff
input <- input[abs(input$dH3K4me1.WT) > s & abs(input$dH3K4me1.dKO) < s & abs(input$dH3K4me1.dCD) < s,]
region <- input$chr %in% c(paste0("chr",1:19),"chrX")
chr <- factor(input$chr[region],levels = c(paste0("chr",1:19),"chrX"))
annotation <- HeatmapAnnotation(df=data.frame("Feature"=c(rep("H3K4me1",3),rep("RT",3),rep("RNA",3))),
                                annotation_height = unit(4,"mm"))
df <- input[region,-1]

library(circlize)
col_fun = colorRamp2(c(-4,-2, 0, 2,4), c("darkblue","dodgerblue", "white", "orange","darkred"))
col_fun = colorRamp2(c(-3, 0, 3), c("dodgerblue", "white", "orange"))

km <-  kmeans(df, 5)
split <- paste0("C\n", km$cluster)
hm <- Heatmap(df, use_raster = T,raster_by_magick = T, top_annotation = annotation, cluster_columns = F, cluster_rows = F, split=split,
        name = "log2(FC)", #title of legend
        column_title=paste0("N=",nrow(df)),
        show_row_dend = F,
        col= col_fun,
        column_labels = c(rep(c("Ctr","dKO","dCD"),3)),
        border=T, row_gap=unit(2,"mm"),
        row_names_gp = gpar(fontsize = 0) # Text size for row names
)
hm <- draw(hm)

##Linear model for H3K4me1 vs RNA contribution to change in RT between dKO and controls during transition
mypar(2,1,mar=c(2.5,6,1.6,1.1))
X <- cbind(dRT$dH3K4me1.dKO-dRT$dH3K4me1.KO,dRT$dRNA.dKO-dRT$dRNA.KO,dRT$dRT.dKO-dRT$dRT.KO)
colnames(X) <- c("ddH3K4me1","ddRNA","ddRT")
X <- as.data.frame(X[complete.cases(X),])
fit <- lm(ddRT ~ .,data=X)
summary(fit)
barplot(coefficients(fit)[-1],las=2,horiz=T,main="dKO")

##Linear model for H3K4me1 vs RNA contribution to change in RT between dCD and controls during transition
X <- cbind(dRT$dH3K4me1.dCD-dRT$dH3K4me1.KO,dRT$dRNA.dCD-dRT$dRNA.KO,dRT$dRT.dCD-dRT$dRT.KO)
colnames(X) <- c("ddH3K4me1","ddRNA","ddRT")
X <- as.data.frame(X[complete.cases(X),])
fit <- lm(ddRT ~ .,data=X)
summary(fit)
coefficients(fit)
barplot(coefficients(fit)[-1],las=2,horiz=T,main="dCD")

##naive RT, H3K4me1 and RNA in mutant vs control at bins that show MLL3/4-dependent H3K4me1
set.seed(178)
input <- dRT[,c(  'chr',
                  'dH3K4me1.naive.dKOvsKO', 'dH3K4me1.naive.dCDvsKO',
                  'dRT.naive.dKOvsKO','dRT.naive.dCDvsKO',
                  'dRNA.naive.dKOvsKO','dRNA.naive.dCDvsKO')]
input <- input[complete.cases(input),]
s=0.5 #cutoff
input <- input[input$dH3K4me1.naive.dKOvsKO < -s & input$dH3K4me1.naive.dCDvsKO < -s,]
region <- input$chr %in% c(paste0("chr",1:19),"chrX")
chr <- factor(input$chr[region],levels = c(paste0("chr",1:19),"chrX"))
annotation <- HeatmapAnnotation(df=data.frame("Feature"=c(rep("H3K4me1",2),rep("RT",2),rep("RNA",2))),
                                annotation_height = unit(4,"mm"))
df <- input[region,-1]

library(circlize)
col_fun = colorRamp2(c(-3, 0, 3), c("dodgerblue", "white", "orange"))
km <-  kmeans(df, 5)

table(km$cluster)

split <- paste0("C\n", km$cluster)

hm <- Heatmap(df, use_raster = T,raster_by_magick = T, top_annotation = annotation, cluster_rows = F,cluster_columns = F, split=split,
        name = "log2(FC)", #title of legend
        column_title=paste0("N=",nrow(df)),
        show_row_dend = F,
        col= col_fun,
        border=T, row_gap=unit(2,"mm"),
        column_labels = c(rep(c("dKO","dCD"),3)),
        row_names_gp = gpar(fontsize = 0) # Text size for row names
)

#Boxplots for each cluster and column
hm <- draw(hm)

#Linear model for H3K4me1 vs RNA contribution to RT changes in naive
##dKO
mypar(2,1,mar=c(2.5,6,1.6,1.1))
X <- cbind(dRT$dH3K4me1.naive.dKOvsKO,dRT$dRNA.naive.dKOvsKO,dRT$dRT.naive.dKOvsKO)
colnames(X) <- c("dH3K4me1","dRNA","dRT")
X <- as.data.frame(X[complete.cases(X),])
fit <- lm(dRT ~ .,data=X)
summary(fit)
barplot(coefficients(fit)[-1],las=2,horiz=T,main="dKO")

##dCD
X <- cbind(dRT$dH3K4me1.naive.dCDvsKO,dRT$dRNA.naive.dCDvsKO,dRT$dRT.naive.dCDvsKO)
colnames(X) <- c("dH3K4me1","dRNA","dRT")
X <- as.data.frame(X[complete.cases(X),])
fit <- lm(dRT ~ .,data=X)
summary(fit)
barplot(coefficients(fit)[-1],las=2,horiz=T,main="dCD")

#Determine significantly changing RT bins among MLL3/4-dependent bins in naive state
set.seed(178)
input <- dRT[,c(  'chr',
                  'dH3K4me1.naive.dKOvsKO', 'dH3K4me1.naive.dCDvsKO',
                  'dRT.naive.dKOvsKO','dRT.naive.dCDvsKO',
                  'dRNA.naive.dKOvsKO','dRNA.naive.dCDvsKO',
                  'KO.naive.n1.RT.Loess','KO.naive.n2.RT.Loess','KO.naive.n3.RT.Loess',
                  'dKO.naive.n1.RT.Loess','dKO.naive.n2.RT.Loess','dKO.naive.n3.RT.Loess',
                  'dCD.naive.n1.RT.Loess','dCD.naive.n2.RT.Loess','dCD.naive.n3.RT.Loess',
                  'AVGnaive.KO','AVGnaive.dKO','dRT.naive.dKOvsKO',
                  'AVGnaive.dCD','dRT.naive.dCDvsKO')]
input <- input[complete.cases(input),]
s=0.5 #cutoff
input <- input[input$dH3K4me1.naive.dKOvsKO < -s & input$dH3K4me1.naive.dCDvsKO < -s,]
region <- input$chr %in% c(paste0("chr",1:19),"chrX")
chr <- factor(input$chr[region],levels = c(paste0("chr",1:19),"chrX"))
annotation <- HeatmapAnnotation(df=data.frame("Feature"=c(rep("H3K4me1",2),rep("RT",2),rep("RNA",2))),
                                annotation_height = unit(4,"mm"))
df <- input[region,-1]

##dKO statistics naive
pval.dRT <- apply(
  cbind(df$dKO.naive.n1.RT.Loess-df$KO.naive.n1.RT.Loess,
        df$dKO.naive.n2.RT.Loess-df$KO.naive.n2.RT.Loess,
        df$dKO.naive.n3.RT.Loess-df$KO.naive.n3.RT.Loess),1,function(row){
          ttest <- t.test(row,mu=0)
          pval <- ttest$p.value
          return(pval)
        }
)

pval.dRT.corr <- p.adjust(pval.dRT,method="fdr")
# Calculate the 2D density using kde2d()
density_est <- kde2d(df$dRT.naive.dKOvsKO,-log10(pval.dRT.corr), n = 250)
# Create a color-coded density heatmap
mycols <- colorRampPalette(c("white", "blue", "red", "orange"))(100)
mypar()
image(density_est, col = mycols, xlab = "naive RT (dKO vs Ctr)", ylab = "-log10(FDR)",xlim=c(-3.5,3.5),ylim=c(0,2),useRaster=T)
abline(h=-log10(0.05),lty=2)
legend("top",legend=paste0(round(100*(sum(pval.dRT.corr < 0.05)/nrow(df)),1),"% of sites"),cex=0.8,box.lty=0,bg="transparent")

#Sankey plot for significantly changing bins
dat_sk <- df[pval.dRT.corr < 0.05,c("AVGnaive.KO","AVGnaive.dKO","dRT.naive.dKOvsKO")]
dim(dat_sk)
dat_sk$ctr.state <- ifelse(dat_sk$AVGnaive.KO > 0,"early","late")
dat_sk$transition.state <- ifelse(dat_sk$dRT.naive.dKOvsKO > 0,"Earlier",
                                  ifelse(dat_sk$dRT.naive.dKOvsKO < 0,"Later","Unchanged"
                                  ))

##Descriptive statistics of changes
table(dat_sk$ctr.state)
table(dat_sk$transition.state)

dat_sk <- dat_sk[,4:5] %>% make_long(ctr.state,transition.state)

dat_sk %>% ggplot(aes(x = x, 
                      next_x = next_x, 
                      node = node, 
                      next_node = next_node,
                      fill = factor(node))) +
  geom_sankey(flow.alpha = 0.75, node.color = "black",flow.color = "black") +
  scale_fill_viridis_d(option = "B", alpha = 0.95) +
  theme_sankey(base_size = 16)

##dCD statistics naive
set.seed(178)
pval.dRT <- apply(
  cbind(df$dCD.naive.n1.RT.Loess-df$KO.naive.n1.RT.Loess,
        df$dCD.naive.n2.RT.Loess-df$KO.naive.n2.RT.Loess,
        df$dCD.naive.n3.RT.Loess-df$KO.naive.n3.RT.Loess),1,function(row){
          ttest <- t.test(row,mu=0)
          pval <- ttest$p.value
          return(pval)
        }
)

pval.dRT.corr <- p.adjust(pval.dRT,method="fdr")
# Calculate the 2D density using kde2d()
density_est <- kde2d(df$dRT.naive.dCDvsKO,-log10(pval.dRT.corr), n = 250)
# Create a color-coded density heatmap
mycols <- colorRampPalette(c("white", "blue", "red", "orange"))(100)
mypar()
image(density_est, col = mycols, xlab = "naive RT (dCD vs Ctr)", ylab = "-log10(FDR)",xlim=c(-3.5,3.5),ylim=c(0,2),useRaster=T)
abline(h=-log10(0.05),lty=2)
legend("top",legend=paste0(round(100*(sum(pval.dRT.corr < 0.05)/nrow(df)),1),"% of sites"),cex=0.8,box.lty=0,bg="transparent")

#Sankey plot
dat_sk <- df[pval.dRT.corr < 0.05,c("AVGnaive.KO","AVGnaive.dCD","dRT.naive.dCDvsKO")]
dim(dat_sk)
dat_sk$ctr.state <- ifelse(dat_sk$AVGnaive.KO > 0,"early","late")
dat_sk$transition.state <- ifelse(dat_sk$dRT.naive.dCDvsKO > 0,"Earlier",
                                  ifelse(dat_sk$dRT.naive.dCDvsKO < 0,"Later","Unchanged"
                                  ))

##Descriptive statistics of changes
table(dat_sk$ctr.state)
table(dat_sk$transition.state)

dat_sk <- dat_sk[,4:5] %>% make_long(ctr.state,transition.state)

dat_sk %>% ggplot(aes(x = x, 
                      next_x = next_x, 
                      node = node, 
                      next_node = next_node,
                      fill = factor(node))) +
  geom_sankey(flow.alpha = 0.75, node.color = "black",flow.color = "black") +
  scale_fill_viridis_d(option = "B", alpha = 0.95) +
  theme_sankey(base_size = 16)

  #EOF